apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: oq6z99my3-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/oq6z99my3-dotnet-basic-gitops